version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'

  mongodb-seed:
    environment:
      - DB_HOSTNAME
    image: mongo:4.4
    depends_on:
      - mongodb
    volumes:
      - ./db:/seed-data
    command: 'bash -c "mongoimport --host mongodb --type json --mode upsert --file /seed-data/listed_buildings.geojson --db poi --collection buildings"'

  buildings:
    build:
      context: ./poi_service
      target: dev
    volumes:
      - ./poi_service/src:/app/src
    depends_on:
      - mongodb-seed
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb
    ports:
      - '8080:8080'

  web_app:
    build:
      context: ./web_app
      target: dev
    depends_on:
      - buildings
    ports:
      - '3000:3000'
    volumes:
      - ./web_app/src:/app/src
      - ./web_app/public:/app/public
    environment:
      - REACT_APP_POI_SERVICE_URI=localhost:8080/buildings
