version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    ports:
      - '${DB_PORT}:${DB_PORT}'

  mongo-seed:
    environment:
      - DB_HOSTNAME
    image: mongo:4.4
    depends_on:
      - mongodb
    volumes:
      - ./db:/seed-data
    command: 'bash -c "mongoimport --host $DB_HOSTNAME --type json --mode upsert --file /seed-data/listed_buildings.geojson --collection buildings"'

  buildings:
    environment:
      - DB_HOSTNAME
    depends_on:
      - mongodb
    ports:
      - '${BUILDINGS_PORT}:${BUILDINGS_PORT}'

  web_app:
    environment:
      - BUILDINGS_PORT
    depends_on:
      - buildings
