org: zackads
app: gromits
service: poi-service

provider:
  name: aws
  region: eu-west-2
  stage: dev
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  # environment:
  #   DB_URL: ${param:dbUrl}
  #   DB_USER: ${param:dbUser}
  #   DB_PASS: ${param:dbPass}

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /buildings/{location}
          method: get
          cors: true
