name: Deployment pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy_webapp:
    name: Deploy Webapp
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2
    defaults:
      run:
        working-directory: web_app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: npm run test
        run: npm run test
      - uses: hashicorp/setup-terraform@v1
      - name: terraform init
        working-directory: web_app/terraform
        run: terraform init
      - name: terraform apply
        working-directory: web_app/terraform
        run: terraform apply -auto-approve -var-file=config.tfvars
      - name: Deploy to S3
        run: aws s3 sync build s3://gromits-webapp

  deploy_poi_service:
    name: Deploy POI Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: poi_service
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm install
        run: npm install
      - name: Install Serverless Framework
        run: npm i -g serverless@2.x
      - name: Authenticate Serverless with AWS
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Deploy
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
