name: CI/CD pipeline
on:
  push:
    branches: [main]

jobs:
  build_service:
    name: Build the Service image and push to ECR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build, tag, and push image to ECR
        run: |
          docker build --target prod -t public.ecr.aws/t1m1t5z8/gromits:service ./buildings_service
          docker push public.ecr.aws/t1m1t5z8/gromits:service

  build_webapp:
    name: Build the Web app image and push to ECR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build, tag, and push image to ECR
        run: |
          docker build --target prod -t public.ecr.aws/t1m1t5z8/gromits:web_app --target prod ./web_app
          docker push public.ecr.aws/t1m1t5z8/gromits:web_app

  deploy:
    name: Deploy to ECS Fargate
    runs-on: ubuntu-latest
    needs: [build_service, build_webapp]

    steps:
      - uses: actions/checkout@v2
      - name: Create ECS Docker context
        run: docker context create ecs gromits --from-env &&
          docker context use gromits
      - name: Bring up cluster
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up
